name: asia_uz
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  easy_localization: ^3.0.0
  mask_text_input_formatter: ^2.1.0
  easy_padding: ^0.1.7
  sms_autofill: ^2.2.0
  get_storage: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  local_auth: ^1.1.11
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.7.0
  http: ^0.13.4
  flash: ^2.0.3+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/
    - assets/images/bg.png


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-SemiBold.ttf
        
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf

